// frontend/bookstore-react/src/components/Client.tsx
import React, { useEffect, useState, ChangeEvent } from 'react';
import { useClientContext } from '../contexts/ClientContext';
import { useResourceContext } from '../contexts/ResourceContext';
import { useRentingContext } from '../contexts/RentingContext';
import { Client } from '../interfaces/Client';
import { ClientRenting } from '../interfaces/Client-renting';
import { Resource } from '../interfaces/Resource';

const ClientComponent: React.FC = () => {
  const { clients, getClients, createClient, updateClient } = useClientContext();
  const { resources } = useResourceContext();
  const { registerRenting, returnRentingResource, listRentingsByClientId } = useRentingContext();

  const [searchString, setSearchString] = useState<string>('');
  const [filteredClients, setFilteredClients] = useState<Client[]>([]);
  const [clientForm, setClientForm] = useState<Client>({ id: '', firstName: '', lastName: '', email: '' });
  const [rentingForm, setRentingForm] = useState<{ resourceId: string, clientId: string, registrationDate: string }>({ resourceId: '', clientId: '', registrationDate: new Date().toISOString().substring(0, 10) });
  const [modalTitle, setModalTitle] = useState<string>('');
  const [clientId, setClientId] = useState<string>('');
  const [rentingList, setRentingList] = useState<ClientRenting[]>([]);
  const [returnDate, setReturnDate] = useState<string>('');

  useEffect(() => {
    getClients();
  }, [getClients]);

  useEffect(() => {
    setFilteredClients(clients.filter(client => client.firstName.toLowerCase().includes(searchString.toLowerCase())));
  }, [clients, searchString]);

  const handleSearch = (e: ChangeEvent<HTMLInputElement>) => {
    setSearchString(e.target.value);
  };

  const handleClientFormChange = (e: ChangeEvent<HTMLInputElement>) => {
    setClientForm({ ...clientForm, [e.target.name]: e.target.value });
  };

  const handleRentingFormChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setRentingForm({ ...rentingForm, [e.target.name]: e.target.value });
  };

  const submitClientModal = async () => {
    if (clientId) {
      await updateClient(clientId, clientForm);
    } else {
      await createClient(clientForm);
    }
    getClients();
  };

  const submitRentingModal = async () => {
    await registerRenting(rentingForm);
  };

  const onNew = () => {
    setModalTitle("New Client");
    setClientId('');
    setClientForm({ id: '', firstName: '', lastName: '', email: '' });
  };

  const onUpdate = (client: Client) => {
    setModalTitle("Update Client");
    setClientId(client.id);
    setClientForm(client);
  };

  const onRenting = async (id: string) => {
    setClientId(id);
    const availableResources = await resources;
    if (availableResources.length > 0) {
      setRentingForm({ resourceId: availableResources[0].id, clientId: id, registrationDate: new Date().toISOString().substring(0, 10) });
    }
  };

  const onReturn = async (id: string) => {
    setClientId(id);
    const rentings = await listRentingsByClientId(id);
    setRentingList(rentings);
  };

  const handleReturnResource = async () => {
    if (clientId && returnDate) {
      await returnRentingResource(clientId, returnDate);
      setReturnDate('');
    }
  };

  return (
    <div className="main-content">
      <div className="container-fluid">
        <div className="row">
          <div className="col-md-12">
            <div className="card">
              <div className="header d-flex flex-column gap-2 p-2">
                <button type="button" data-bs-toggle="modal" data-bs-target="#newModal" data-bs-backdrop="false" onClick={onNew} className="btn btn-success">New +</button>
                <div className="form-group">
                  <div className="input-group padding-top">
                    <div className="input-group-text">
                      <i className="bi bi-search"></i>
                    </div>
                    <input type="text" className="form-control" name="searchString" placeholder="Type to search..." value={searchString} onChange={handleSearch} />
                  </div>
                </div>
              </div>
              <div className="content table-responsive table-full-width">
                <table className="table table-hover table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Email</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredClients.map((client) => (
                      <tr key={client.id}>
                        <td>{client.id}</td>
                        <td>{client.firstName}</td>
                        <td>{client.lastName}</td>
                        <td>{client.email}</td>
                        <td>
                          <button type="button" data-bs-toggle="modal" data-bs-target="#newModal" onClick={() => onUpdate(client)} data-bs-backdrop="false" className="btn btn-info">Edit <i className="bi bi-pencil"></i></button>
                          <button type="button" data-bs-toggle="modal" data-bs-target="#rentingModal" onClick={() => onRenting(client.id)} data-bs-backdrop="false" className="btn btn-secondary">Renting <i className="bi bi-file-earmark-font"></i></button>
                          <button type="button" data-bs-toggle="modal" data-bs-target="#returnModal" onClick={() => onReturn(client.id)} data-bs-backdrop="false" className="btn btn-warning">Return <i className="bi bi-arrow-counterclockwise"></i></button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* New Client Modal */}
      <div className="modal" id="newModal">
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">{modalTitle}</h4>
            </div>
            <div className="modal-body">
              <form>
                <div className="row gy-2">
                  <div className="form-group col-xs-12">
                    <label htmlFor="firstName">First Name:</label>
                    <input type="text" name="firstName" className="form-control" placeholder="Name" value={clientForm.firstName} onChange={handleClientFormChange} />
                  </div>
                  <div className="form-group col-xs-12">
                    <label htmlFor="lastName">Last Name:</label>
                    <input type="text" name="lastName" className="form-control" placeholder="Last Name" value={clientForm.lastName} onChange={handleClientFormChange} />
                  </div>
                  <div className="form-group col-xs-12">
                    <label htmlFor="email">Email:</label>
                    <input type="email" name="email" className="form-control" placeholder="Email" value={clientForm.email} onChange={handleClientFormChange} />
                  </div>
                </div>
              </form>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" onClick={submitClientModal} data-bs-dismiss="modal">Ok</button>
              <button type="button" className="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      {/* Renting Modal */}
      <div className="modal" id="rentingModal">
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">Register Renting</h4>
            </div>
            <div className="modal-body">
              <form>
                <div className="row gy-2">
                  <div className="form-group col-xs-12">
                    <label htmlFor="resourceId">Resource:</label>
                    <select className="form-control" name="resourceId" value={rentingForm.resourceId} onChange={handleRentingFormChange}>
                      {resources.map((resource: Resource) => (
                        <option key={resource.id} value={resource.id}>{resource.name}</option>
                      ))}
                    </select>
                  </div>
                  <div className="form-group col-xs-12">
                    <label htmlFor="registrationDate">Date:</label>
                    <input type="date" name="registrationDate" className="form-control" value={rentingForm.registrationDate} onChange={handleRentingFormChange} />
                  </div>
                </div>
              </form>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" onClick={submitRentingModal} data-bs-dismiss="modal">Ok</button>
              <button type="button" className="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      {/* Return Modal */}
      <div className="modal fade" id="returnModal">
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">Return</h4>
            </div>
            <div className="modal-body">
              <div className="row gy-2">
                <div className="col-md-12">
                  <div className="card">
                    <div className="content table-responsive table-full-width">
                      <table className="table table-hover table-striped">
                        <thead>
                          <tr>
                            <th>Resource</th>
                            <th>Registration Date</th>
                          </tr>
                        </thead>
                        <tbody>
                          {rentingList.map((renting) => (
                            <tr key={renting.id}>
                              <td>{renting.resourceName}</td>
                              <td>{new Date(renting.registrationDate).toLocaleDateString()}</td>
                              <td>
                                <button type="button" data-bs-toggle="modal" data-bs-target="#dateModal" onClick={() => setClientId(renting.id)} data-bs-backdrop="false" className="btn btn-info" data-bs-dismiss="modal">
                                  Return <i className="bi bi-arrow-counterclockwise"></i>
                                </button>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      {/* Date Modal */}
      <div className="modal fade" id="dateModal">
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">Select Return Date</h4>
            </div>
            <div className="modal-body">
              <div className="row gy-2">
                <div className="form-group col-xs-12">
                  <label>Date:</label>
                  <input type="date" className="form-control" value={returnDate} onChange={(e) => setReturnDate(e.target.value)} />
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" onClick={handleReturnResource} data-bs-dismiss="modal" disabled={!returnDate}>Ok</button>
              <button type="button" className="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ClientComponent;

// frontend/bookstore/src/app/client/client.component.ts
import { Component } from '@angular/core';
import { ClientService } from './client.service';
import { debounceTime, map } from 'rxjs/operators';
import { BehaviorSubject, Observable, Subject, combineLatest, firstValueFrom } from 'rxjs';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { AsyncPipe, DatePipe, NgFor } from '@angular/common';
import { Resource } from '../resource/resource';
import { ResourceService } from '../resource/resource.service';
import { Client } from './client';
import { RentingService } from './renting.service';
import { ClientRenting } from './client-renting';

@Component({
  selector: 'app-client',
  standalone: true,
  imports: [NgFor, AsyncPipe, DatePipe, FormsModule, ReactiveFormsModule],
  templateUrl: './client.component.html',
  styleUrl: './client.component.css'
})
export class ClientComponent {
  tableColumns = ['ID', 'First Name','Last Name', 'Email'];
  loadedClients: Subject<Client[]> = new Subject();
  tableRows: Observable<Client[]>;
  searchString?: string;
  search: BehaviorSubject<string> = new BehaviorSubject('');
  resources: Observable<Resource[]>;
  rentingList?: Observable<ClientRenting[]>;
  clientForm: FormGroup;
  rentingGroup: FormGroup;
  modalTitle?: string;
  id?: string;
  date?: Date;

  handleSearch(evt: Event) {
    this.search.next((evt.target as HTMLInputElement).value);
  }

  constructor(
    private readonly clientService: ClientService,
    private readonly rentingService: RentingService,
    resourceService: ResourceService
  ) {
    this.getClients();
    this.tableRows = combineLatest([
      this.search.pipe(debounceTime(300)),
      this.loadedClients,
    ]).pipe(map(([searchText, data]) => {
      if (!searchText) return data;
      return data.filter(d => d.firstName.toLowerCase().includes(searchText.toLowerCase()));//TODO we may need to add lastName as well
    }));

    this.resources = resourceService.getList();

    this.rentingGroup = new FormGroup({
      resourceId: new FormControl('', [Validators.required]),
      clientId: new FormControl('', [Validators.required]),
      registrationDate: new FormControl(new Date(Date.now()), [Validators.required])
    });

    this.clientForm = new FormGroup({
      firstName: new FormControl('', [Validators.required]),
      lastName: new FormControl('', [Validators.required]),
      email: new FormControl('', [Validators.required])
    });
  }

  getClients() {
    this.clientService.getList().subscribe(clients => {
      this.loadedClients.next(clients);
    });
  }

  submitClientModal() {
    const client: Client = this.clientForm.value;
    if (this.id) {
      this.clientService.update(this.id, client).subscribe(() => {
        this.getClients();
      });
    }
    else {
      this.clientService.create(client).subscribe(() => {
        this.getClients();
      });;
    }
  }

  returnResource() {
    console.error(this.id, this.date);
    if(!this.id) return;

    if(!this.date) return;

     this.rentingService.returnResource(this.id, this.date).subscribe(() => {
       // Handle update
     });
  }

  returnSpecificResource() {
    console.error(this.id, this.date);
    if(!this.id) return;

    if(!this.date) return;

     this.rentingService.returnSpecificResource(this.id, this.date).subscribe(() => {
       // Handle update
     });
  }

  deleteClient() {
    if(!this.id) return;
    this.clientService.delete(this.id);
  }

  onNew() {
    this.modalTitle = "New Client";
    this.id = undefined;
  }

  onUpdate(row: any) {
    this.modalTitle = "Update Client";
    this.id = row.id;
    this.clientForm.reset();
    this.clientForm.patchValue(row);
  }

  submitRentingModal() {
    const renting = this.rentingGroup.value;
    this.rentingService.register(renting).subscribe((_) => {
      // Handle register
    });
  }

  async onRenting(id: string) {
    const loadedResources = await firstValueFrom(this.resources);
    if(!loadedResources.length) return;
    
    this.rentingGroup.reset();
    this.rentingGroup.patchValue({
      resourceId: loadedResources[0].id,
      clientId: id
    });
  }

  onReturn(id: string) {
    this.id = id;
    this.rentingList = this.rentingService.listByClientId(id);
  }

  onReturnDate(id: string,returnDate: Date|undefined) {
    this.id = id;
    this.date = undefined;
    this.rentingService.returnSpecificResource(id,returnDate);
  }
}

<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header d-flex flex-column gap-2 p-2">
                        <div>
                            <button type="button" data-bs-toggle="modal" data-bs-target="#newModal" data-bs-backdrop="false"
                            (click)="onNew()" class="btn btn-success">New +</button>
                        </div>
                        <div class="form-group">
                            <div class="input-group padding-top">
                                <div class="input-group-text">
                                  <i class="bi bi-search"></i>
                                </div>
                                <input type="text" class="form-control" name="searchString"
                                    placeholder="Type to search..." [(ngModel)]="searchString"
                                    (input)="handleSearch($event)" />
                            </div>
                        </div>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th *ngFor="let column of tableColumns">{{ column }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let row of tableRows | async let i = index">
                                    <td>{{row.id}}</td>
                                    <td>{{row.firstName}}</td>
                                    <td>{{row.lastName}}</td>
                                    <td>{{row.email}}</td>
                                    <td>
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#newModal"
                                            (click)="onUpdate(row)" data-bs-backdrop="false"
                                            class="btn btn-info">
                                            Edit <i class="bi bi-pencil"></i>
                                        </button>
                                        </td>
                                    <td>
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#rentingModal"
                                            (click)="onRenting(row.id)" data-bs-backdrop="false" [disabled]="!(resources | async)?.length"
                                            class="btn btn-secondary">
                                            Renting <i class="bi bi-file-earmark-font"></i>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#returnModal"
                                            (click)="onReturn(row.id)" data-bs-backdrop="false"
                                            class="btn btn-warning">
                                            Return <i class="bi bi-arrow-counterclockwise"></i>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="newModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">{{modalTitle}}</h4>
                </div>

                <div class="modal-body">
                    <form novalidate [formGroup]="clientForm">
                        <div class="row gy-2">
                            <div class="form-group col-xs-12">
                                <label for="firstName">First Name:</label>
                                <input type="text" formControlName="firstName" class="form-control" placeholder="Name">
                            </div>
                            <div class="form-group col-xs-12">
                                <label for="lastName">Last Name:</label>
                                <input type="text" formControlName="lastName" class="form-control" placeholder="Name">
                            </div>
                            <div class="form-group col-xs-12">
                                <label for="Email">Email:</label>
                                <input type="text" formControlName="email" class="form-control" placeholder="Email">
                            </div>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" (click)="submitClientModal()"
                        data-bs-dismiss="modal">Ok</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="rentingModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Renting</h4>
                </div>

                <div class="modal-body">
                    <form novalidate [formGroup]="rentingGroup">
                        <div class="row gy-2">
                            <div class="form-group col-xs-12">
                                <label>Resource:</label>
                                <select formControlName="resourceId" class="form-control">
                                    <option *ngFor="let resource of resources | async; let i = index;" async
                                        [value]="resource.id" [selected]="i === 0">
                                        {{resource.name}}
                                    </option>
                                </select>
                            </div>
                            <div class="form-group col-xs-12">
                                <label>Date:</label>
                                <input type="date" formControlName="registrationDate" class="form-control">
                            </div>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" (click)="submitRentingModal()"
                        data-bs-dismiss="modal">Ok</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="returnModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Return</h4>
                </div>

                <div class="modal-body">
                    <div class="row gy-2">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="content table-responsive table-full-width">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Resource
                                                </th>
                                                <th>
                                                    Registration Date
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr *ngFor="let row of rentingList | async">
                                                <td>{{row.resourceName}}</td>
                                                <td>{{row.registrationDate | date}}</td>
                                                <td>
                                                    <button type="button" data-bs-toggle="modal"
                                                        data-bs-target="#dateModal" (click)="onReturnDate(row.id,date)"
                                                        data-bs-backdrop="false" class="btn btn-info"
                                                        data-bs-dismiss="modal">
                                                        Return <i class="bi bi-arrow-counterclockwise"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="dateModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Select Return Date</h4>
                </div>

                <div class="modal-body">
                    <div class="row gy-2">
                        <div class="form-group col-xs-12">
                            <label>Date:</label>
                            <input type="date" [(ngModel)]="date" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" (click)="returnSpecificResource()" data-bs-dismiss="modal" [disabled]="!date">Ok</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

</div>
