// frontend/bookstore/src/app/inventory/inventory.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { InventoryService } from './inventory.service';
import { BehaviorSubject, Observable, combineLatest, debounceTime, map } from 'rxjs';
import { AsyncPipe, NgFor } from '@angular/common';
import { InventorySummary } from './inventory-summary';

@Component({
  selector: 'app-inventory',
  standalone: true,
  imports: [NgFor, AsyncPipe, FormsModule],
  templateUrl: './inventory.component.html',
  styleUrl: './inventory.component.css'
})
export class InventoryComponent {
  tableColumns: string[] = ['ID', 'Name', 'Available Copies', 'Unavailable Copies', 'Total'];
  searchString?: string;
  data: Observable<InventorySummary[]>;
  tableRows: Observable<InventorySummary[]>;
  search: BehaviorSubject<string> = new BehaviorSubject('');

  constructor(private readonly inventoryService: InventoryService) {
    this.data = this.inventoryService.getSummary();
    this.tableRows = combineLatest([
      this.search.pipe(debounceTime(300)),
      this.data,
    ]).pipe(map(([searchText, data]) => {
      if(!searchText) return data;
      return data.filter(d => d.resourceName.toLowerCase().includes(searchText.toLowerCase()));
    }));
  }

  handleSearch(evt: Event) {
    this.search.next((evt.target as HTMLInputElement).value);
  }
}

<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header p-2">
                        <div class="form-group">
                            <div class="input-group">
                              <div class="input-group-text">
                                <i class="bi bi-search"></i>
                              </div>
                              <input
                                type="text"
                                class="form-control"
                                name="searchString"
                                placeholder="Type to search..."
                                [(ngModel)]="searchString"
                                (input)="handleSearch($event)"
                              />
                            </div>
                          </div>
                    </div>
                    <div class="content table-responsive table-full-width">
                          <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th *ngFor="let column of tableColumns">{{ column }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr *ngFor="let row of tableRows | async">
                                        <td>{{row.resourceId}}</td>
                                        <td>{{row.resourceName}}</td>
                                        <td>{{row.availableCopies}}</td>
                                        <td>{{row.unavailableCopies}}</td>
                                        <td>{{row.totalCopies}}</td>
                                    </tr>
                                </tbody>
                          </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend/bookstore-react/src/components/Inventory.tsx
import React, { useEffect, useState, ChangeEvent } from 'react';
import { useInventoryContext } from '../contexts/InventoryContext';
import { InventorySummary } from '../interfaces/Inventory-summary';

const InventoryComponent: React.FC = () => {
  const { inventorySummary, getInventorySummary } = useInventoryContext();
  const [searchString, setSearchString] = useState<string>('');
  const [filteredInventory, setFilteredInventory] = useState<InventorySummary[]>([]);

  useEffect(() => {
    getInventorySummary();
  }, [getInventorySummary]);

  useEffect(() => {
    setFilteredInventory(inventorySummary.filter(item => 
      item.resourceName.toLowerCase().includes(searchString.toLowerCase())
    ));
  }, [inventorySummary, searchString]);

  const handleSearch = (e: ChangeEvent<HTMLInputElement>) => {
    setSearchString(e.target.value);
  };

  return (
    <div className="main-content">
      <div className="container-fluid">
        <div className="row">
          <div className="col-md-12">
            <div className="card">
              <div className="header p-2">
                <div className="form-group">
                  <div className="input-group">
                    <div className="input-group-text">
                      <i className="bi bi-search"></i>
                    </div>
                    <input 
                      type="text" 
                      className="form-control" 
                      name="searchString" 
                      placeholder="Type to search..." 
                      value={searchString} 
                      onChange={handleSearch} 
                    />
                  </div>
                </div>
              </div>
              <div className="content table-responsive table-full-width">
                <table className="table table-hover table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Available Copies</th>
                      <th>Unavailable Copies</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredInventory.map((row) => (
                      <tr key={row.resourceId}>
                        <td>{row.resourceId}</td>
                        <td>{row.resourceName}</td>
                        <td>{row.availableCopies}</td>
                        <td>{row.unavailableCopies}</td>
                        <td>{row.totalCopies}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InventoryComponent;
