// Frontend/src/app/navbar/navbar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { routeItems } from '../layouts/admin-layout/admin-layout.routes';
import { NavigationEnd, Router } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  title: string = 'Dashboard';
  @Output() onToggle = new EventEmitter<void>();

  constructor(private readonly router: Router) {
    this.router.events.pipe(filter(evt => evt instanceof NavigationEnd)).subscribe((_) => {
      const activeRoute = routeItems.find(item => this.router.isActive(item.path, false));
      this.title = activeRoute?.title ?? 'Dashboard';
    });
  }
}

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <button type="button" class="navbar-toggler d-md-none" (click)="onToggle.next()">
            <i class="bi bi-list"></i>
        </button>
        <label class="navbar-brand">{{title}}</label>
    </div>
</nav>

// frontend/bookstore-react/src/components/Navbar.tsx
import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { routeItems } from '../routes/routeItems';

const Navbar = () => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [title, setTitle] = useState('Dashboard');
  const location = useLocation();

  useEffect(() => {
    const activeRoute = routeItems.find(item => location.pathname === item.path);
    setTitle(activeRoute ? activeRoute.title : 'Dashboard');
  }, [location]);

  const toggleNavbar = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <nav className="navbar navbar-light bg-light">
      <div className="container-fluid">
        <button type="button" className="navbar-toggler d-md-none" onClick={toggleNavbar}>
          <i className="bi bi-list"></i>
        </button>
        <span className="navbar-brand">{title}</span>
      </div>
    </nav>
  );
};

export default Navbar;
