// Frontend/src/app/sidebar/sidebar.component.ts
import { NgIf, NgFor, NgClass } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NavigationEnd, Router, RouterLink, RouterLinkActive } from '@angular/router';
import { routeItems } from '../layouts/admin-layout/admin-layout.routes';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, RouterLink, RouterLinkActive],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {
  @Output() onToggle = new EventEmitter<void>();
  @Input() expanded: boolean = false;
  menuItems = routeItems;

  constructor(router: Router) {
    router.events.pipe(filter(evt => evt instanceof NavigationEnd))
      .subscribe(() => {
        if(window.matchMedia("(min-width: 768px)") && this.expanded) {
          this.onToggle.next();
        }
      })
  }
}

<div class="d-flex flex-column flex-shrink-0 p-3 bg-light h-100">
    <div class="d-flex gap-2 align-items-center justify-content-md-center link-dark text-decoration-none fs-4">
        <button type="button" class="navbar-toggler d-md-none" (click)="onToggle.next()">
            <i class="bi bi-list"></i>
        </button>
        <i class="bi bi-book"></i>
        <span>Bookstore</span>
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item" *ngFor="let item of menuItems">
            <a href="#" class="nav-link" [routerLink]="item.path" routerLinkActive="active">
                <i [ngClass]="item.icon"></i>
                {{ item.title }}
            </a>
        </li>
    </ul>
</div>

// frontend/bookstore-react/src/components/Sidebar.tsx
import React, { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { routeItems } from '../routes/routeItems';


const Sidebar: React.FC = () => {

    const [expanded, setExpanded] = useState(false);

    const toggleSidebar = () => {
        setExpanded(!expanded);
      };

    return (
        <div className={`d-flex flex-column flex-shrink-0 p-3 bg-light h-100 ${expanded ? 'expanded' : ''}`}>
            <div className="d-flex gap-2 align-items-center justify-content-md-center link-dark text-decoration-none fs-4">
                <button type="button" className="navbar-toggler d-md-none" onClick={toggleSidebar}>
                    <i className="bi bi-list"></i>
                </button>
                <i className="bi bi-book"></i>
                <span>Bookstore</span>
            </div>
            <hr />
            <ul className="nav nav-pills flex-column mb-auto">
                {routeItems.map((item) => (
                    <li className="nav-item" key={item.path}>
                        <NavLink
                            to={item.path}
                            className={({ isActive }) =>
                                isActive ? 'active' : ''
                            }
                        >
                            <i className={item.icon}></i>
                            {item.title}
                        </NavLink>
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default Sidebar;
